backend:
  name: test-repo

media_folder: static/img
public_folder: /img

collections:
  - name: pages
    label: Pages
    files:
      - file: src/pages/index.md
        label: Home Page
        name: Home Page
        fields:
          - {label: Template Key, name: templateKey, widget: hidden, default: index-page}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: About Section Heading, name: about_section_heading, widget: string}
          - {label: About Section Description, name: aboutSectionDescription, widget: markdown}
          - {label: About Section Image, name: aboutSectionImage, widget: image}
          - {label: About Section Button, name: aboutSectionButton, widget: string}
      - file: src/pages/story.md
        label: Story
        name: story
        fields:
          - {label: Template Key, name: templateKey, widget: hidden, default: story-page}
          - label: Story Images
            name: storyImages
            widget: list
            fields: 
            - {label: Image, name: image, widget: image}
            - {label: Caption, name: caption, widget: string}
          - label: Copy Section,
            name: copySection,
            widget: list
            fields: 
              - {label: Title, name: title, widget: string}
              - {label: Description, name: description, widget: markdown}